### ISSUE TITLE
County-wide subdomain block  

### ISSUE THREAD

**Issue by drippy-cat** [joalricha869/bitlifeUnblocked#3]
Hi! Your subdomain appears to be blocked in my county. Do you have any ideas on how to fix this? Thanks! Edit: I know how to unblock the website on my individual computer but I think we should find a way to globally unblock it.
![Screenshot 2023-02-28 10 58 41 AM](https://user-images.githubusercontent.com/95929812/221908562-f0815bcd-d409-4ca1-9c31-4e0b4b33d0cb.png)

**Comment by joalricha869** [comment]
what proxy does your computer/browser use? also, it seems that ```github.io``` links are blocked by your proxy.

I can help with that, I have an unblocker... 

try this?: https://haven.lucasmunoz8.repl.co/?unlock

**Comment by joalricha869** [comment]
Also, there might be other stuff which isn't blocked which you can find here:

https://docs.google.com/document/d/1yx9DPGEl-57uo0OtHHkz0ALBjTph_gDMyEik03V3br8/edit?usp=sharing

**Comment by drippy-cat** [comment]
Both of those are blocked. `github.io` is not blocked. It's just certain user's subdomains. 
![Screenshot 2023-02-28 5 29 28 PM](https://user-images.githubusercontent.com/95929812/221996437-ec33cdad-c6a8-4961-8862-5cd6d9ddfcd5.png)
![Screenshot 2023-02-28 5 29 24 PM](https://user-images.githubusercontent.com/95929812/221996440-d044555e-6576-48ad-8f0a-342c27e994e6.png)

**Comment by joalricha869** [comment]
damn, well there is another link

https://dingusorg.github.io/yeet

**Comment by drippy-cat** [comment]
Thanks that one works!

**Comment by drippy-cat** [comment]
I'll try to find a way to unblock your subdomain for other users as well (including other people who might have it blocked in their county).

**Comment by joalricha869** [comment]
yup for some reason im blocked lmao there we be based in ```dont want to reveal my district to avoid getting doxxed```

**Comment by drippy-cat** [comment]
Haha. Thankfully mine hasn't gotten blocked yet.

**Comment by joalricha869** [comment]
rip virginia

**Comment by joalricha869** [comment]
[Biology Homework (1).docx](https://github.com/joalricha869/bitlifeUnblocked/files/10855347/Biology.Homework.1.docx)

heres the google doc

**Comment by drippy-cat** [comment]
Thanks!

**Comment by joalricha869** [comment]
glad to help! if u need any help or need a new link, here's my discord: joalricha#8877

**Comment by drippy-cat** [comment]
Ok cool. Thanks!
